name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH for EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$EC2_SSH_KEY" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
    - name: Deploy to EC2
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa $EC2_USER@$EC2_IP << 'EOF'
          # Update system and install necessary dependencies
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git
          sudo apt install -y nodejs npm git postgresql redis-server
          sudo systemctl enable postgresql
          sudo systemctl start postgresql
          sudo systemctl enable redis-server
          # Set up PostgreSQL for Medusa-backend
          sudo -u postgres psql -c "CREATE USER medusa WITH PASSWORD 'medusa';" || true
          sudo -u postgres psql -c "CREATE DATABASE medusa;" || true
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE medusa TO medusa;" || true
           # Grant additional permissions to the user
          sudo -u postgres psql -d medusa -c "GRANT ALL PRIVILEGES ON SCHEMA public TO medusa;"
          # Configure PostgreSQL authentication method
          sudo sh -c 'echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/16/main/pg_hba.conf'
           # Reload PostgreSQL to apply configuration changes
          sudo systemctl reload postgresql
          # Install Medusa CLI
          sudo npm install -g @medusajs/medusa-cli
          # Create a new Medusa project
          mkdir medusa-backend && cd medusa-backend
          sudo medusa new . --skip-db
          # Update the .env file to connect to the correct PostgreSQL database
          echo "DATABASE_URL=postgres://medusa:medusa@localhost:5432/medusa" | sudo tee .env
          sudo chown $USER:$USER .env && chmod 644 .env
          
          # run migrations
          sudo medusa migrations run
          # set admin user-name and password 
          sudo medusa user --email sarthak@gmail.com --password sarthak
          # Start Medusa backend
          nohup sudo medusa start &> medusa.log &
        EOF
